# Use root/example as user/password credentials
version: '3.1'
services:
  mongodb:    
    image: mongo  
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodbdata:/data/db    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  mongo-express:
    image: mongo-express  
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - mongodbdata:/data/db    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    networks:
      - backend

 
  streamlit:    
    build: .
    container_name: streamlit    
    volumes:
      - "./../../:/app/"    
    ports:
      - "8501:8501"
      - "5000:5000" 
    command: bash -c "python cygnss-deployment/prefect-deploy.py  && streamlit run cygnss-deployment/dashboard.py && mlflow ui -p 5000"      
    depends_on:
    - mongodb
    networks:
      - backend


  # If needed, uncomment below code block 
#  prefect:  
#    image: prefecthq/prefect
#    ports:
#      - "8000:8000"      
  

    
networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
