FROM ubuntu:20.04

ARG DOCKER_TAG

ENV ENV_NAME=cygnss-d

# the base image does not have wget
RUN apt-get update
RUN apt-get install -y wget

# Following the description here:
# https://towardsdatascience.com/conda-pip-and-docker-ftw-d64fe638dc45

SHELL [ "/bin/bash", "--login", "-c" ]

# The kernel environment needs to be copied as root
# Assumes the docker build context as the git project root directory
COPY ./docker/kernel-env-cuda11.yaml /tmp/

USER root

# install miniconda (using fixed version)
ENV MINICONDA_VERSION 4.10.3
ENV CONDA_DIR $HOME/miniconda3
#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-$MINICONDA_VERSION-Linux-x86_64.sh -O ~/miniconda.sh  
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O ~/miniconda.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p $CONDA_DIR  && \
    rm ~/miniconda.sh

# make non-activate conda commands available
ENV PATH=$CONDA_DIR/bin:$PATH

# make conda activate command available from /bin/bash --login shells
RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile

# make conda activate command available from /bin/bash --interative shells
RUN source ~/.bashrc
RUN conda init bash

# create a project directory inside user home
ENV PROJECT_DIR $HOME/app
RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR

# build the conda environment
#ENV ENV_PREFIX $PWD/env
RUN conda update --name base --channel defaults conda && \
    conda env create --file /tmp/kernel-env-cuda11.yaml --force && \
    conda clean --all --yes
