apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-orion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-orion
  template:
    metadata:
      labels:
        app: prefect-orion
    spec:
      containers:
      - name: prefect-orion
        image: prefecthq/prefect:2.6.8-python3.11
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "700Mi"
            cpu: "500m"
        ports:
        - containerPort: 4200
