version: '3.7'

services:
  torchserve-mar: # container-name
    image: torchserve-mar:v1
    ports:
      - "8080:8080"
      - "8081:8081" 
  mnistapp:
    build: app/
    ports:
      - "9696:9696"
